"""Project binding and clean, ownership-checked removal."""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path
import subprocess
import sys
from typing import Any

from .errors import AvatarRuntimeError
from .manifest import PROJECT_INSTALL_SCHEMA, load_manifest
from .paths import (
    atomic_write_json,
    atomic_write_text,
    model_directory,
    project_runtime_directory,
    read_json,
    remove_owned_tree,
    resolve_registry,
)


INSTALLATION_FILE = "installation.json"
PROJECT_MANIFEST_FILE = "RUNTIME-MANIFEST.md"
PROJECT_DOCTOR_SCHEMA = "live2d-avatar/project-doctor/v0.1"
VOICE_SELECTION_SCHEMA = "codex-ai-presence/avatar-selection/v0.1"
VOICE_AVATAR_SCHEMA = "codex-ai-presence/avatar/v0.1"
VOICE_STATE_STATUS_SCHEMA = "codex-ai-presence/avatar-state-status/v0.1"
VOICE_STATE_CAPABILITY = "avatar-state-v1"
BUNDLE_OWNERSHIP_SCHEMA = "live2d-avatar/bundle-ownership/v0.1"
CAPABILITY_SCHEMA = "live2d-avatar/capabilities/v0.1"


def _now() -> str:
    return datetime.now(UTC).isoformat().replace("+00:00", "Z")


def _project_manifest_text(
    project: Path,
    model_id: str,
    registry: Path,
    created_at: str,
    installation: dict[str, Any] | None = None,
) -> str:
    external_paths = installation.get("owned_external_paths", []) if installation else []
    external_rows = "\n".join(f"- `{path}`" for path in external_paths) or "- None."
    bridge_rows = (
        "- `.codex-live2d/bundles/`\n- `.codex-live2d/avatar-state-revisions.json`"
        if installation and "bundles/" in installation.get("owned_paths", [])
        else "- None."
    )
    context_hook = installation.get("context_hook") if installation else None
    context_hook_rows = (
        "- `.codex-live2d/live2d_context_hook.py`\n"
        "- One managed `UserPromptSubmit` handler in `.codex/hooks.json` (the file and other handlers remain user-owned)."
        if isinstance(context_hook, dict)
        else "- None."
    )
    process_rows = (
        "A short-lived `UserPromptSubmit` context hook runs once per Codex turn. It starts no watcher, daemon, listener, port, or socket."
        if isinstance(context_hook, dict)
        else "None. This version does not start a watcher, service, renderer, port, or socket."
    )
    return f"""# Managed Live2D Avatar Runtime Manifest

This file is generated by `live2d-avatar project install`. It records the exact resources owned by the Live2D runtime for this project installation.

| Field | Value |
| --- | --- |
| Owner | `live2d-avatar-runtime` |
| Install schema | `{PROJECT_INSTALL_SCHEMA}` |
| Created | `{created_at}` |
| Project | `{project}` |
| Selected model | `{model_id}` |
| Registry | `{registry}` |

## Owned project-local resources

- `.codex-live2d/installation.json`
- `.codex-live2d/RUNTIME-MANIFEST.md`

## Materialized renderer resources

{bridge_rows}

## Optional agent-context hook resources

{context_hook_rows}

## Owned external project resources

{external_rows}

## Processes and listeners

{process_rows}

## External resources intentionally not owned here

- Imported assets at `{registry / model_id}` are global model-registry resources. Remove them only with `live2d-avatar model remove {model_id} --yes`.
- `.codex-voice` files and processes remain owned by `codex-voice`.

## Removal

Run `live2d-avatar project uninstall --project "{project}" --yes`. The command validates `installation.json`, removes this `.codex-live2d` boundary, unregisters only this runtime's optional `UserPromptSubmit` handler, and removes only external avatar bundles carrying this runtime's `bundle-ownership.json` marker.
"""


def install_project(project: Path, model_id: str, registry: Path, *, replace: bool = False) -> dict[str, Any]:
    project = project.expanduser().resolve()
    if not project.is_dir():
        raise AvatarRuntimeError(f"project directory does not exist: {project}")
    registry = resolve_registry(registry)
    load_manifest(registry, model_id)
    runtime = project_runtime_directory(project)
    marker = runtime / INSTALLATION_FILE
    previous_installation: dict[str, Any] | None = None
    if runtime.exists():
        if not replace:
            raise AvatarRuntimeError(
                f"project runtime already exists: {runtime}; pass --replace to update its binding"
            )
        if runtime.is_symlink() or not runtime.is_dir():
            raise AvatarRuntimeError(f"refusing to replace non-directory runtime path: {runtime}")
        existing = read_json(marker)
        if (
            existing.get("schema") != PROJECT_INSTALL_SCHEMA
            or existing.get("owner") != "live2d-avatar-runtime"
        ):
            raise AvatarRuntimeError(f"refusing to replace a runtime not owned by this tool: {runtime}")
        previous_model_id = existing.get("model_id")
        if previous_model_id != model_id:
            raise AvatarRuntimeError(
                "project is already bound to a different model; run project uninstall before changing models"
            )
        previous_installation = existing
    created_at = _now()
    installation = {
        "schema": PROJECT_INSTALL_SCHEMA,
        "owner": "live2d-avatar-runtime",
        "created_at": created_at,
        "model_id": model_id,
        "registry": str(registry),
        "owned_paths": [INSTALLATION_FILE, PROJECT_MANIFEST_FILE],
        "owned_processes": [],
        "owned_listeners": [],
    }
    if previous_installation is not None:
        previous_owned_paths = previous_installation.get("owned_paths", [])
        if not isinstance(previous_owned_paths, list) or not all(
            isinstance(item, str) for item in previous_owned_paths
        ):
            raise AvatarRuntimeError("project installation has invalid owned paths")
        installation["owned_paths"] = sorted(
            set(installation["owned_paths"])
            | {item for item in previous_owned_paths if item in {"bundles/", "avatar-state-revisions.json"}}
        )
        expected_external_bundle = str(project / ".codex-voice-avatars" / model_id)
        previous_external_paths = previous_installation.get("owned_external_paths", [])
        if not isinstance(previous_external_paths, list) or not all(
            isinstance(item, str) for item in previous_external_paths
        ):
            raise AvatarRuntimeError("project installation has invalid external ownership paths")
        if previous_external_paths:
            if previous_external_paths != [expected_external_bundle]:
                raise AvatarRuntimeError("project installation has unexpected external avatar ownership")
            installation["owned_external_paths"] = previous_external_paths
        previous_hook = previous_installation.get("context_hook")
        if isinstance(previous_hook, dict) and (runtime / "live2d_context_hook.py").is_file():
            installation["context_hook"] = previous_hook
            installation["owned_paths"] = sorted(
                set(installation["owned_paths"]) | {"live2d_context_hook.py"}
            )
    atomic_write_json(marker, installation)
    atomic_write_text(runtime / PROJECT_MANIFEST_FILE, _project_manifest_text(project, model_id, registry, created_at, installation))
    return {
        "project": str(project),
        "runtime": str(runtime),
        "model_id": model_id,
        "registry": str(registry),
        "status": "installed",
    }


def project_status(project: Path) -> dict[str, Any]:
    project = project.expanduser().resolve()
    runtime = project_runtime_directory(project)
    marker = runtime / INSTALLATION_FILE
    if not runtime.exists():
        return {"project": str(project), "runtime": str(runtime), "status": "not-installed"}
    if runtime.is_symlink():
        return {"project": str(project), "runtime": str(runtime), "status": "invalid", "error": "symbolic link"}
    try:
        installation = read_json(marker)
    except AvatarRuntimeError as exc:
        return {"project": str(project), "runtime": str(runtime), "status": "invalid", "error": str(exc)}
    if installation.get("schema") != PROJECT_INSTALL_SCHEMA:
        return {
            "project": str(project),
            "runtime": str(runtime),
            "status": "invalid",
            "error": "unexpected installation schema",
        }
    return {"project": str(project), "runtime": str(runtime), "status": "installed", "installation": installation}


def _optional_document(path: Path) -> dict[str, Any] | None:
    try:
        return read_json(path)
    except AvatarRuntimeError:
        return None


def _bundle_diagnostics(project: Path, installation: dict[str, Any], model_id: str) -> dict[str, Any]:
    """Inspect the external renderer bundle without modifying Voice-owned state."""

    bundle = project / ".codex-voice-avatars" / model_id
    if not bundle.exists():
        return {"status": "missing", "owned": False, "state_capable": False}
    if bundle.is_symlink() or not bundle.is_dir():
        return {"status": "invalid", "owned": False, "state_capable": False}
    expected_path = str(bundle)
    owned_paths = installation.get("owned_external_paths", [])
    recorded = isinstance(owned_paths, list) and expected_path in owned_paths
    ownership = _optional_document(bundle / "bundle-ownership.json")
    owned = bool(
        recorded
        and ownership is not None
        and ownership.get("schema") == BUNDLE_OWNERSHIP_SCHEMA
        and ownership.get("owner") == "live2d-avatar-runtime"
        and ownership.get("project") == str(project)
        and ownership.get("model_id") == model_id
    )
    avatar = _optional_document(bundle / "avatar.json")
    capabilities = _optional_document(bundle / "avatar-capabilities.json")
    advertised = avatar.get("capabilities") if avatar is not None else []
    state_capable = bool(
        avatar is not None
        and avatar.get("schema") == VOICE_AVATAR_SCHEMA
        and avatar.get("id") == model_id
        and isinstance(advertised, list)
        and VOICE_STATE_CAPABILITY in advertised
        and capabilities is not None
        and capabilities.get("schema") == CAPABILITY_SCHEMA
        and capabilities.get("avatar_id") == model_id
    )
    if owned and state_capable:
        status = "ready"
    elif not owned:
        status = "unowned"
    else:
        status = "incomplete"
    return {"status": status, "owned": owned, "state_capable": state_capable}


def _selection_diagnostics(project: Path, model_id: str) -> dict[str, Any]:
    selection = _optional_document(project / ".codex-voice" / "avatar-selection.json")
    if selection is None:
        return {"status": "missing"}
    selected_id = selection.get("avatar_id")
    if selection.get("schema") != VOICE_SELECTION_SCHEMA or not isinstance(selected_id, str):
        return {"status": "invalid"}
    return {
        "status": "selected" if selected_id == model_id else "different-avatar",
        "avatar_id": selected_id,
    }


def _voice_state_diagnostics(project: Path, model_id: str) -> dict[str, Any]:
    status = _optional_document(project / ".codex-voice" / "avatar-state-status.json")
    if status is None:
        return {"status": "missing"}
    if status.get("schema") != VOICE_STATE_STATUS_SCHEMA or status.get("type") != "avatar-state-status":
        return {"status": "invalid"}
    if status.get("avatar_id") != model_id:
        return {"status": "stale-avatar"}
    accepted = status.get("accepted")
    revision = status.get("revision")
    action_count = status.get("action_count")
    if not isinstance(accepted, bool) or not isinstance(revision, int) or not isinstance(action_count, int):
        return {"status": "invalid"}
    return {
        "status": "accepted" if accepted else "rejected",
        "revision": revision,
        "action_count": action_count,
    }


def project_doctor(project: Path) -> dict[str, Any]:
    """Return a bounded, read-only readiness report for the generic workflow."""

    project = project.expanduser().resolve()
    status = project_status(project)
    if status.get("status") != "installed":
        return {
            "schema": PROJECT_DOCTOR_SCHEMA,
            "project": str(project),
            "status": "not-bound" if status.get("status") == "not-installed" else "invalid",
            "next_steps": ["Import a model, then run project bind with its model id."],
        }
    installation = status.get("installation")
    if not isinstance(installation, dict):
        raise AvatarRuntimeError("project installation is invalid")
    model_id = installation.get("model_id")
    registry_value = installation.get("registry")
    if not isinstance(model_id, str) or not isinstance(registry_value, str):
        raise AvatarRuntimeError("project installation has no model binding")

    model: dict[str, Any] = {"id": model_id, "status": "missing"}
    try:
        manifest = load_manifest(Path(registry_value), model_id)
    except AvatarRuntimeError:
        manifest = None
    if manifest is not None:
        profile = manifest.get("profile")
        if not isinstance(profile, dict):
            semantic_status = "unprofiled"
            profile_name = None
        else:
            candidate = profile.get("semantic_status", "draft")
            semantic_status = candidate if isinstance(candidate, str) and candidate in {"draft", "curated"} else "invalid"
            profile_name = profile.get("name") if isinstance(profile.get("name"), str) else None
        model = {
            "id": model_id,
            "status": "available",
            "action_count": len(manifest["actions"]),
            "semantic_status": semantic_status,
            "profile_name": profile_name,
        }

    bundle = _bundle_diagnostics(project, installation, model_id)
    selection = _selection_diagnostics(project, model_id)
    voice_root = project / ".codex-voice"
    voice = {
        "avatar_installer": "available" if (voice_root / "avatar.py").is_file() else "missing",
        "state_writer": "available" if (voice_root / "avatar_state.py").is_file() else "missing",
        "renderer_state": _voice_state_diagnostics(project, model_id),
    }
    try:
        from .hook_registration import context_hook_status

        hook = context_hook_status(project).get("status", "unavailable")
    except AvatarRuntimeError:
        hook = "unavailable"

    next_steps: list[str] = []
    if model.get("status") != "available":
        next_steps.append("Re-import or restore the selected managed model.")
    elif model.get("semantic_status") == "unprofiled":
        next_steps.append("Create a user-owned profile draft, review it visually, and apply a curated semantic profile.")
    elif model.get("semantic_status") == "draft":
        next_steps.append("Visually review the profile draft and mark its semantic_status curated before relying on agent context.")
    elif model.get("semantic_status") == "invalid":
        next_steps.append("Repair the profile semantic_status before using the avatar context hook.")
    if voice["avatar_installer"] != "available":
        next_steps.append("Install Codex Voice before materializing the avatar renderer.")
    if bundle["status"] != "ready":
        next_steps.append("Run project bind to materialize and select the managed avatar bundle.")
    if selection["status"] != "selected":
        next_steps.append("Use project bind so Codex Voice selects the intended managed avatar.")
    if voice["state_writer"] != "available":
        next_steps.append("Install the Codex Voice avatar-state writer before publishing state.")
    elif voice["renderer_state"].get("status") != "accepted":
        next_steps.append("Publish the current semantic action set and verify Voice acceptance.")

    ready = not next_steps
    return {
        "schema": PROJECT_DOCTOR_SCHEMA,
        "project": str(project),
        "status": "ready" if ready else "needs-attention",
        "model": model,
        "bundle": bundle,
        "selection": selection,
        "voice": voice,
        "context_hook": hook,
        "next_steps": next_steps,
    }


def bind_project(project: Path, model_id: str, registry: Path, *, replace: bool = False) -> dict[str, Any]:
    """Install and materialize one generic model binding without bypassing Voice."""

    project = project.expanduser().resolve()
    registry = resolve_registry(registry)
    load_manifest(registry, model_id)
    existing = project_status(project)
    installed_now = existing.get("status") == "not-installed"
    if installed_now:
        install_project(project, model_id, registry)
    elif existing.get("status") != "installed":
        raise AvatarRuntimeError("project runtime is invalid; repair or uninstall it before binding an avatar")
    else:
        installation = read_project_installation(project)
        if installation.get("model_id") != model_id:
            raise AvatarRuntimeError(
                "project is bound to a different model; run project uninstall before binding another model"
            )
        if replace:
            install_project(project, model_id, registry, replace=True)

    installation = read_project_installation(project)
    bundle = _bundle_diagnostics(project, installation, model_id)
    selection = _selection_diagnostics(project, model_id)
    external_bundle = project / ".codex-voice-avatars" / model_id
    if external_bundle.exists() and not bundle["owned"]:
        raise AvatarRuntimeError("refusing to replace an external avatar bundle not owned by this runtime")
    if bundle["status"] == "ready" and selection["status"] == "selected" and not replace:
        return {
            "project": str(project),
            "model_id": model_id,
            "status": "already-bound",
            "restart_required": False,
        }
    if bundle["status"] == "incomplete" and not replace:
        raise AvatarRuntimeError("managed avatar bundle is incomplete; pass --replace to refresh it")

    # Local import avoids a lifecycle <-> bundle import cycle. materialize_bundle
    # invokes Voice's installer with --use; this runtime never writes selection.
    from .bundle import materialize_bundle

    materialized = materialize_bundle(project, model_id, registry, replace=external_bundle.exists())
    return {
        "project": str(project),
        "model_id": model_id,
        "status": "bound" if installed_now else "refreshed",
        "materialized": materialized,
        "restart_required": True,
    }


def read_project_installation(project: Path) -> dict[str, Any]:
    project = project.expanduser().resolve()
    runtime = project_runtime_directory(project)
    installation = read_json(runtime / INSTALLATION_FILE)
    if installation.get("schema") != PROJECT_INSTALL_SCHEMA or installation.get("owner") != "live2d-avatar-runtime":
        raise AvatarRuntimeError("project runtime is not owned by this tool")
    return installation


def uninstall_project(project: Path, *, confirm: bool) -> dict[str, Any]:
    if not confirm:
        raise AvatarRuntimeError("project uninstall requires --yes")
    project = project.expanduser().resolve()
    runtime = project_runtime_directory(project)
    installation = read_json(runtime / INSTALLATION_FILE)
    if installation.get("schema") != PROJECT_INSTALL_SCHEMA or installation.get("owner") != "live2d-avatar-runtime":
        raise AvatarRuntimeError("refusing to remove a runtime directory without this install marker")
    # The JSON-aware removal preserves voice and user handlers in hooks.json.
    if installation.get("context_hook") is not None:
        from .hook_registration import disable_context_hook

        disable_context_hook(project, for_uninstall=True)
    for external_path in installation.get("owned_external_paths", []):
        if not isinstance(external_path, str):
            raise AvatarRuntimeError("project installation has an invalid external ownership path")
        bundle = Path(external_path)
        bundle_root = project / ".codex-voice-avatars"
        try:
            bundle.resolve().relative_to(bundle_root.resolve())
        except ValueError as exc:
            raise AvatarRuntimeError("project installation external path escapes the avatar bundle root") from exc
        ownership = read_json(bundle / "bundle-ownership.json")
        if (
            ownership.get("schema") != "live2d-avatar/bundle-ownership/v0.1"
            or ownership.get("owner") != "live2d-avatar-runtime"
            or ownership.get("project") != str(project)
        ):
            raise AvatarRuntimeError("refusing to remove an external avatar bundle without our ownership marker")
        model_id = ownership.get("model_id")
        if not isinstance(model_id, str):
            raise AvatarRuntimeError("external avatar bundle ownership marker has no model id")
        selection_path = project / ".codex-voice" / "avatar-selection.json"
        if selection_path.exists():
            selection = read_json(selection_path)
            if selection.get("avatar_id") == model_id:
                avatar_tool = project / ".codex-voice" / "avatar.py"
                if not avatar_tool.is_file():
                    raise AvatarRuntimeError("cannot deselect an active managed avatar because Codex Voice is unavailable")
                completed = subprocess.run(
                    [sys.executable, str(avatar_tool), "--project-root", str(project), "use", "builtin"],
                    capture_output=True,
                    text=True,
                    encoding="utf-8",
                    errors="replace",
                )
                if completed.returncode != 0:
                    raise AvatarRuntimeError("could not deselect the active managed avatar before uninstall")
        remove_owned_tree(bundle, bundle_root)
    remove_owned_tree(runtime, project)
    return {"project": str(project), "runtime": str(runtime), "status": "removed"}


def remove_model(registry: Path, model_id: str, *, confirm: bool) -> dict[str, Any]:
    if not confirm:
        raise AvatarRuntimeError("model removal requires --yes")
    registry = resolve_registry(registry)
    manifest = load_manifest(registry, model_id)
    lifecycle = manifest.get("lifecycle")
    if not isinstance(lifecycle, dict) or lifecycle.get("owner") != "live2d-avatar-runtime":
        raise AvatarRuntimeError("refusing to remove a model not owned by this runtime")
    target = model_directory(registry, model_id)
    remove_owned_tree(target, registry)
    return {"id": model_id, "registry": str(registry), "status": "removed"}
